name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]

    steps:
      - if: matrix.os == 'windows'
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - run: docker/start.sh

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - run: zig version

      - run: zig build test -freference-trace --summary all -Doptimize=${{ matrix.optimize }}

